### ISSUE TITLE
Kanban Board Set-up

### ISSUE THREAD

**Issue by jsug9** [jsug9/Catalog-Capstone#54]
### Hello
Kindly check our [Github Project](https://github.com/jsug9/Catalog-Capstone/projects/1).
For this project, we are a group of 3 composed by:
- Augusto Galindo: [@jsug9](https://github.com/jsug9)
- Catherine Kemigabo: [@kemigabocatherine](https://github.com/kemigabocatherine)
- Sediqullah Badakhsh: [@sediqullahbadakhsh](https://github.com/sediqullahbadakhsh)

We have divided the tasks into group, student A, B and C In the following way:
- Group tasks: Everyone.
- Student A: Sediqullah Badakhsh
- Student B: Augusto Galindo
- Student C: Catherine Kemigabo

**Comment by julie-ify** [comment]
Hi @jsug9, @kemigabocatherine and @sediqullahbadakhsh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
